name: Web & Api WorkFLow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-web-automation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.3.0

    - name: Setup gradlew
      run: chmod +x gradlew 

    - name: Execute Web Test
      run: ./gradlew cucumberWebTest

  run-api-automation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.3.0

    - name: Setup gradlew
      run: chmod +x gradlew 

    - name: Execute Web Test
      run: ./gradlew cucumberApiTest
